import type { Metadata } from 'next'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import BookingForm from '@/components/BookingForm'
import PopularDestinations from '@/components/PopularDestinations'
import { BreadcrumbJsonLd, FAQJsonLd } from '@/components/JsonLd'
import { ArrowRight, CheckCircle, ShieldCheck, Fuel } from 'lucide-react'

export const metadata: Metadata = {
  title: 'One Way Taxi Bareilly | One Way Cab Drops starting ₹11/km',
  description: 'Book one-way outstation taxis from Bareilly to Delhi, Noida, Lucknow, Nainital, and Haridwar. Pay only for one-way distance at ₹11/km. Verified drivers.',
  alternates: {
    canonical: 'https://sambhujitravels.in/one-way-taxi-bareilly',
  },
}

const oneWayFAQs = [
  {
    question: 'Do I have to pay for the return fare of the taxi?',
    answer: 'No! When you book our one-way drop taxi service, you only pay for the one-way distance from Bareilly to your destination. There are absolutely no return trip charges.',
  },
  {
    question: 'What are the main one-way drop routes from Bareilly?',
    answer: 'Our top one-way destinations are Delhi NCR (Delhi, Noida, Gurgaon, Ghaziabad), Lucknow, Haridwar, Nainital, Haldwani, Kathgodam, and Dehradun.',
  },
  {
    question: 'Are there any hidden fees like driver allowances in one-way trips?',
    answer: 'No. All one-way quotes generated by our team include the driver allowance, vehicle fuel, and maintenance charges. Toll taxes and state permits are separate and paid as per actual receipts.',
  },
]

export default function OneWayTaxiBareilly() {
  return (
    <>
      <BreadcrumbJsonLd
        items={[
          { name: 'Home', url: 'https://sambhujitravels.in' },
          { name: 'One Way Taxi Bareilly', url: 'https://sambhujitravels.in/one-way-taxi-bareilly' },
        ]}
      />
      <FAQJsonLd faqs={oneWayFAQs} />
      <Header />
      
      <main className="bg-gray-50/50">
        <section className="bg-primary text-white py-16 relative overflow-hidden">
          <div className="absolute inset-0 opacity-10 bg-[radial-gradient(#ffffff_1px,transparent_1px)] [background-size:16px_16px]"></div>
          <div className="container mx-auto px-4 relative z-10">
            <h1 className="text-3xl md:text-5xl font-extrabold mb-4 leading-tight">
              One-Way Outstation Taxis from Bareilly
            </h1>
            <p className="text-blue-100 text-base md:text-lg max-w-3xl leading-relaxed">
              Pay only for the distance you travel. Premium one-way outstation drops from Bareilly to major North Indian cities. Sedan ₹11/km, SUV ₹13/km.
            </p>
          </div>
        </section>

        <section className="py-12">
          <div className="container mx-auto px-4">
            <div className="grid lg:grid-cols-3 gap-8 items-start">
              <div className="lg:col-span-2 space-y-8">
                
                <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-150">
                  <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center gap-2">
                    <ArrowRight className="text-primary" />
                    Save Money with Bareilly One-Way Taxis
                  </h2>
                  <p className="text-gray-655 text-sm md:text-base leading-relaxed mb-4">
                    Why pay for a round-trip fare when you are only traveling one way? Shambhu Ji Travels provides dedicated one-way drop outstation taxis from Bareilly. Save up to 50% on your travel cost by paying strictly for the distance from your pickup point to your final drop-off location.
                  </p>
                  <p className="text-gray-650 text-sm md:text-base leading-relaxed">
                    We offer standard per-kilometer pricing (₹11/km for AC Sedan, ₹13/km for AC SUV) and operate a fleet of modern, clean, and commercial-permit cabs driven by background-checked professional chauffeurs.
                  </p>
                </div>

                {/* Popular One-way destinations */}
                <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-150">
                  <h3 className="text-xl font-bold text-gray-800 mb-6">Popular One-Way Fares from Bareilly</h3>
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="p-4 border border-gray-100 rounded-xl hover:shadow-sm transition-all bg-gray-50/50">
                      <h4 className="font-bold text-gray-850 text-sm">Bareilly to Delhi NCR Drop</h4>
                      <p className="text-xs text-gray-400">Distance: ~250 km • Sedan starts ₹2,750</p>
                    </div>
                    <div className="p-4 border border-gray-100 rounded-xl hover:shadow-sm transition-all bg-gray-50/50">
                      <h4 className="font-bold text-gray-850 text-sm">Bareilly to Lucknow Drop</h4>
                      <p className="text-xs text-gray-400">Distance: ~250 km • Sedan starts ₹2,750</p>
                    </div>
                    <div className="p-4 border border-gray-100 rounded-xl hover:shadow-sm transition-all bg-gray-50/50">
                      <h4 className="font-bold text-gray-850 text-sm">Bareilly to Haridwar Drop</h4>
                      <p className="text-xs text-gray-400">Distance: ~280 km • Sedan starts ₹3,080</p>
                    </div>
                    <div className="p-4 border border-gray-100 rounded-xl hover:shadow-sm transition-all bg-gray-50/50">
                      <h4 className="font-bold text-gray-850 text-sm">Bareilly to Dehradun Drop</h4>
                      <p className="text-xs text-gray-400">Distance: ~300 km • Sedan starts ₹3,300</p>
                    </div>
                  </div>
                </div>

                {/* Features & Guarantees */}
                <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-150">
                  <h3 className="text-xl font-bold text-gray-800 mb-6">Our One-Way Service Guarantees</h3>
                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="flex gap-4">
                      <div className="bg-blue-50 text-primary p-3 rounded-xl h-11 w-11 flex items-center justify-center shrink-0">
                        <CheckCircle size={20} />
                      </div>
                      <div>
                        <h4 className="font-bold text-gray-800 text-sm mb-1">True One-Way Billing</h4>
                        <p className="text-gray-500 text-xs leading-relaxed">No return mileage is charged. Fares are calculated only for the one-way distance between cities.</p>
                      </div>
                    </div>
                    <div className="flex gap-4">
                      <div className="bg-green-50 text-green-600 p-3 rounded-xl h-11 w-11 flex items-center justify-center shrink-0">
                        <ShieldCheck size={20} />
                      </div>
                      <div>
                        <h4 className="font-bold text-gray-800 text-sm mb-1">No Sharing / Full Cab</h4>
                        <p className="text-gray-500 text-xs leading-relaxed">We do not offer shared cabs. You get the entire private vehicle for your family or group.</p>
                      </div>
                    </div>
                    <div className="flex gap-4">
                      <div className="bg-orange-50 text-orange-600 p-3 rounded-xl h-11 w-11 flex items-center justify-center shrink-0">
                        <Fuel size={20} />
                      </div>
                      <div>
                        <h4 className="font-bold text-gray-800 text-sm mb-1">Well-Maintained AC Vehicles</h4>
                        <p className="text-gray-500 text-xs leading-relaxed">Cabs are strictly serviced, clean, and fully operational for long outstation routes.</p>
                      </div>
                    </div>
                    <div className="flex gap-4">
                      <div className="bg-purple-50 text-purple-600 p-3 rounded-xl h-11 w-11 flex items-center justify-center shrink-0">
                        <ArrowRight size={20} />
                      </div>
                      <div>
                        <h4 className="font-bold text-gray-800 text-sm mb-1">Zero Hidden Charges</h4>
                        <p className="text-gray-500 text-xs leading-relaxed">Transparent invoicing. Driver allowance is built-in; tolls are charged strictly on actuals.</p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* FAQ section */}
                <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-150">
                  <h3 className="text-xl font-bold text-gray-800 mb-4">FAQs about One-Way Taxis</h3>
                  <div className="space-y-4">
                    {oneWayFAQs.map((faq, index) => (
                      <details key={index} className="bg-gray-50 rounded-xl border border-gray-150 group">
                        <summary className="flex items-center justify-between p-4 cursor-pointer font-bold text-gray-800 hover:text-primary transition-colors text-sm select-none">
                          {faq.question}
                          <svg className="w-5 h-5 text-gray-500 group-open:rotate-180 transition-transform flex-shrink-0 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </summary>
                        <div className="px-4 pb-4 text-gray-655 text-xs leading-relaxed border-t border-gray-100 pt-3">
                          {faq.answer}
                        </div>
                      </details>
                    ))}
                  </div>
                </div>

              </div>

              <div className="space-y-6">
                <div className="sticky top-24">
                  <BookingForm />
                </div>
              </div>
            </div>
          </div>
        </section>

        <PopularDestinations />
      </main>

      <Footer />
    </>
  )
}
